//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace B2_2NET_Mini_Projet1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Driver
    {
        public Driver()
        {
            this.Last_Name = "Default_Last_Name";
            this.First_Name = "Default_First_Name";
            this.Car_Model = "Default_Car_Model";
            this.Trips = new HashSet<Trips>();
        }
    
        public int Id { get; set; }
        public string Last_Name { get; set; }
        public string First_Name { get; set; }
        public string Car_Model { get; set; }
        public int Age { get; set; }
        public int Salary { get; set; }
        public int Campus { get; set; }
        public string City { get; set; }
    
        public virtual ICollection<Trips> Trips { get; set; }
    }
}
