//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace B2_2NET_Mini_Projet1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trips
    {
        public int Id { get; set; }
        public string Departure { get; set; }
        public string Departure_Time { get; set; }
        public string Arrival { get; set; }
        public string Arrival_Time { get; set; }
        public string Client_First_Name { get; set; }
        public string Client_Last_Name { get; set; }
        public int DriverId { get; set; }
    
        public virtual Driver Driver { get; set; }
    }
}
